on:
  schedule:
    - cron: 30 4 * * *

jobs:
  trigger-nightly:
    name: Trigger Nightly Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Trigger Nightly Build
        run: ./.ci/nightly-build "${COMMIT_ID}"
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          COMMIT_ID: ${{ github.sha }}
