on:
  push:
    tags: 'v*'

jobs:
  trigger-release:
    name: Trigger Installers Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Trigger Build
        run: ./.ci/release "${TAG}" "${COMMIT_ID}"
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          TAG: ${{ github.ref }}
          COMMIT_ID: ${{ github.sha }}
